development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ticket-tracker_production
  pool: 5
  timeout: 5000
  username: <%= ENV['ticket-tracker_DATABASE_USER'] %>
  password: <%= ENV['ticket-tracker_DATABASE_PASSWORD'] %>